doctors/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('',views.doctors, name="doctors"),
    path('profile/<str:pk>', views.doc_profile, name="doc_profile"),
    path('self_doc/', views.self_doc, name="self_doc"),
    path('find_patient/', views.find_patient, name="find_patient"),
    path('otp_page/', views.otp_page, name="otp_page"),
    path('otp_result/', views.otp_result, name="otp_result"),
    path('inbox/', views.inbox, name="inbox"),
]

healthify/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import  settings
from django.conf.urls.static import static

urlpatterns = [
    path('noentry/', admin.site.urls),
    path('patient/', include('patient.urls')),
    path('labs/', include('labs.urls')),
    path('doctors/', include('doctors.urls')),
    path('', include('administration.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

labs/urls.py
from . import views
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', views.lab_home, name='lab_home'),
]

doctors/models.py
from django.db import models
import uuid


class Doctor(models.Model):
    name = models.CharField(max_length=200, null=True, blank=True)
    qualification = models.CharField(max_length=200, null=True, blank=True)
    email = models.EmailField(max_length=200, null=True, blank=True)
    short_intro = models.CharField(max_length=500, null=True, blank=True)
    bio = models.TextField(max_length=1000, null=True, blank=True)
    profile_image = models.ImageField(max_length=200,null=True, blank=True, upload_to='doctors/', default="doctors/user-default.png")
    college = models.CharField(max_length=200,null=True, blank=True)
    current_hospital = models.CharField(max_length=200,null=True, blank=True)
    votes = models.IntegerField(default=0, null=True, blank=True)
    votes_ratio = models.IntegerField(default=0, null=True, blank=True)
    social_github = models.CharField(max_length=200,null=True, blank=True)
    location = models.CharField(max_length=200, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4,primary_key=True, unique=True, editable=False)

    def __str__(self):
        return str(self.name)

    class Meta:
        ordering = ['-votes_ratio']

class Special(models.Model):
    owner = models.ForeignKey(Doctor, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=20, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.name) 


class Review(models.Model):
    VOTE_TYPE = (('up', 'Up Vote'), ('down', 'Down Vote'))
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    body = models.TextField(max_length=100)
    value = models.CharField(max_length=100, choices=VOTE_TYPE)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4,
                          primary_key=True, unique=True, editable=False)

    def __str__(self):
        return self.value

doctors/views.py
from django.shortcuts import render, redirect
from .models import Doctor,Special
from django.shortcuts import render
from django.http import HttpResponse
from django.core.mail import send_mail
import math, random
from patient.models import patient
from django.db.models import Q
from labs.models import report


def doctors(request):
    doctors = Doctor.objects.all()
    search_query = ''
    special = ''
    if request.GET.get('text'):
        search_query = request.GET.get('text')
        special = Special.objects.filter(name__icontains=search_query)
        doctors = Doctor.objects.distinct().filter(Q(name__icontains=search_query) | Q(short_intro__icontains=search_query) | Q(special__in=special))
    return render(request, 'doctors/doctors.html', {'doctors' : doctors,'search_query' : search_query})

def doc_profile(request, pk):
    profile = Doctor.objects.get(id=pk)
    patients = patient.objects.get(name="Rohan Gupta")
    return render(request, 'doctors/doc_profile.html', {'profile' : profile, "patient" : patients})

def self_doc(request):
    profile = Doctor.objects.get(name="Aviral Nagpal")
    return render(request, 'doctors/self_doc.html', {'profile' : profile})

def find_patient(request):
    return render(request, 'doctors/find_patient.html')

def otp_page(request):
    if request.method == "POST":
        otp = request.POST.get('otp')
        if(otp=="RohanMittal"):
            return redirect('dashboard')
        elif(otp=="lalpathlab"):
            return redirect('lab_home')
    return render(request, 'doctors/otp_page.html')

def otp_result(request):
    patients = patient.objects.get(name="Rohan Gupta")
    doctors = Doctor.objects.get(name="Aviral Nagpal")
    reports = report.objects.filter(adhar=patients.adhar)
    return render(request, "doctors/otp_result.html",{'patient' : patients, "reports" : reports, 'doctor' : doctors})

def inbox(request):
    return render(request, 'doctors/inbox.html')

doctors/templates/doctors/doc_profile.html
{% extends 'main.html' %}

{% block title %}
Doctor - {{ profile.name }}
{% endblock %}

{% block content %}

<main class="profile my-md">
    <div class="container">
        <div class="layout">
            <div class="column column--1of3">
                <div class="card text-center">
                    <div class="card__body dev">
                        <img class="avatar avatar--xl" src="{{ profile.profile_image.url }}" />
                        <h2 class="dev__name">{{profile.name}}</h2>
                        <p class="dev__title">{{profile.short_intro}}</p>
                        <p class="dev__location">Based in {{profile.location}}</p>
                        <ul class="dev__social">
                            <a href="#" class="btn btn--sub btn--lg">Send Message </a>

                        </ul>
                    </div>
                </div>
            </div>
            <div class="column column--2of3">
                <div class="devInfo">
                    <h3 class="devInfo__title">About Me</h3>
                    <p class="devInfo__about">{{profile.bio}}</p>
                </div>
                <div class="devInfo">
                    <h3 class="devInfo__title">Specialization</h3>
                    <div class="devInfo__skills">

                        {% for spec in profile.special_set.all %}
                        <div class="devSkill">
                            <h4 class="devSkill__title">{{spec.name}}</h4>
                            <p class="devSkill__info">{{spec.description}}</p>
                        </div>
                        {% endfor %}
                        <div class="comments">
                            <h3 class="singleProject__subtitle">Feedback</h3>
                            <h5 class="project--rating">
                                {{profile.votes_ratio}}% Positive Feedback ({{profile.votes}}
                                Vote{{profile.votes|pluralize:"s"}})
                            </h5>
                
                            <form class="form" action="#" method="POST">
                              <!-- Textarea -->
                              <div class="form__field">
                                <label for="formInput#textarea">Comments: </label>
                                <textarea class="input input--textarea" name="message" id="formInput#textarea"
                                  placeholder="Write your comments here..."></textarea>
                              </div>
                              <input class="btn btn--sub btn--lg" type="submit" value="Comments" />
                            </form>
                            <div class="commentList">
                              <div class="comment">
                                <a href="#">
                                  <img class="avatar avatar--md" src="{{patient.profile_image.url}}" alt="user" />
                                </a>
                                <div class="comment__details">
                                  <a href="#" class="comment__author">{{patient.name}}</a>
                                  <p class="comment__info">
                                    Good Doctor!
                                  </p>
                                </div>
                              </div>
                            </div>
                          </div>
            </div>
        </div>
    </div>
</main>

{% endblock %}

doctors/templates/doctors/doctors.html
{% extends 'main.html' %}

{% block content %}

<main class="home">
    <section class="hero-section text-center">
      <div class="container container--narrow">
        <div class="hero-section__box">
          <h2>CONNECT WITH <span>DOCTORS</span></h2>
          <h2>FROM AROUND THE WORLD</h2>
        </div>

        <div class="hero-section__search">
          <form id="searchForm" class="form" action="{% url 'doctors' %}" method="get">
            <div class="form__field">
              <label for="formInput#search">Search Doctors</label>
              <input class="input input--text" id="formInput#search" type="text" name="text"
                placeholder="Search Doctors" value="{{search_query}}"/>
            </div>

            <input class="btn btn--sub btn--lg" type="submit" value="Search" />
          </form>
        </div>
      </div>
    </section>
    <!-- Search Result: DevList -->
    <section class="devlist">
      <div class="container">
        <div class="grid grid--three">
        {% for doctor in doctors %}  
          <div class="column card">
            <div class="dev">
              <a href="{% url 'doc_profile' doctor.id %}" class="card__body">
                <div class="dev__profile">
                  <img class="avatar avatar--md" src={{doctor.profile_image.url}} alt="image" />
                  <div class="dev__meta">
                    <h3>{{doctor.name}}</h3>
                    <h5>{{doctor.qualification}}</h5>
                  </div>
                </div>
                <p class="dev__info">
                  {{doctor.bio|slice:"150"}}
                </p>
                <div class="dev__skills">
                  {% for spec in doctor.special_set.all|slice:"5" %}  
                  <span class="tag tag--pill tag--main">
                    <small>{{spec.name}}</small>
                  </span>
                  {% endfor %}
                </div>
              </a>
            </div>
          </div>
        {% endfor %}  
        </div>
      </div>
    </section>

    {% comment %} {% include 'users/pagination.html' with users=users custom_page=custom_page %} {% endcomment %}

  </main>

{% endblock %}

doctors/templates/doctors/find_patient.html
{% load static %}
<html lang="en">

    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      
        <!-- Favicon -->
        <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
        <!-- Icon - IconMonster -->
        <link rel="stylesheet" href="https://cdn.iconmonstr.com/1.3.0/css/iconmonstr-iconic-font.min.css" />
        <!-- Mumble UI -->
        <link rel="stylesheet" href="{% static 'uikit/styles/uikit.css' %}" />
        <!-- Dev Search UI -->
        <link rel="stylesheet" href="{% static "styles/app.css" %}" />
      
        <title>Find Patient!</title>
      </head>

<body>
    <!-- Header Section -->
    <header class="header">
        <div class="container container--narrow">
          <a href="{% url 'self_doc' %}" class="header__logo">
            <img src="{% static 'images/logo.png' %}" alt="DevSearch Logo" />
          </a>
          <nav class="header__nav">
            <input type="checkbox" id="responsive-menu" />
            <label for="responsive-menu" class="toggle-menu">
              <span>Menu</span>
              <div class="toggle-menu__lines"></div>
            </label>
            <ul class="header__menu">
              <li class="header__menuItem"><a href="{% url 'find_patient' %}">Find Patients</a></li>
              <li class="header__menuItem"><a href="{% url 'inbox' %}">Inbox</a></li>
              <li class="header__menuItem"><a href="{% url 'landing' %}" class="btn btn--sub">Logout</a></li>
            </ul>
          </nav>
        </div>
      </header>

    <!-- Main Section -->
    <main class="formPage my-xl">
        <div class="content-box">


                <form class="form" method="POST">
                    <!-- Input:Text -->
                    <div class="form__field">
                        <label for="formInput#text">Enter Patient Aadhar Number: </label>
                        <input class="input input--text" id="formInput#text" type="text" name="text"
                            placeholder="Enter Patient Aadhar Number" />
                    </div>

                    <a href="{% url 'otp_page' %}"><input class="btn btn--sub btn--lg  my-md" type="button" value="Next" /></a>
                </form>
            </div>
        </div>
    </main>
</body>

</html>

doctors/templates/doctors/inbox.html
{% load static %}
<html lang="en">

    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      
        <!-- Favicon -->
        <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
        <!-- Icon - IconMonster -->
        <link rel="stylesheet" href="https://cdn.iconmonstr.com/1.3.0/css/iconmonstr-iconic-font.min.css" />
        <!-- Mumble UI -->
        <link rel="stylesheet" href="{% static 'uikit/styles/uikit.css' %}" />
        <!-- Dev Search UI -->
        <link rel="stylesheet" href="{% static "styles/app.css" %}" />
      
        <title>Inbox</title>
      </head>

<body>
    <!-- Header Section -->
    <header class="header">
        <div class="container container--narrow">
          <a href="{% url 'self_doc' %}" class="header__logo">
            <img src="{% static 'images/logo.png' %}" alt="DevSearch Logo" />
          </a>
          <nav class="header__nav">
            <input type="checkbox" id="responsive-menu" />
            <label for="responsive-menu" class="toggle-menu">
              <span>Menu</span>
              <div class="toggle-menu__lines"></div>
            </label>
            <ul class="header__menu">
              <li class="header__menuItem"><a href="{% url 'find_patient' %}">Find Patients</a></li>
              <li class="header__menuItem"><a href="{% url 'inbox' %}">Inbox</a></li>
              <li class="header__menuItem"><a href="{% url 'landing' %}" class="btn btn--sub">Logout</a></li>
            </ul>
          </nav>
        </div>
      </header>

  <!-- Main Section -->
  <main class="inbox my-xl">
    <div class="content-box">
      <h3 class="inbox__title">New Messages(<span>2</span>)</h3>
      <ul class="messages">
        <li class="message message--unread">
          <a href="message.html">
            <span class="message__author">Rohan Gupta</span>
            <span class="message__subject">Doctor When is my appointment?</span>
            <span class="message__date">Feb 12, 2022, 04:37 PM</span>
          </a>
        </li>
        <li class="message message--unread">
          <a href="message.html">
            <span class="message__author">Karnika</span>
            <span class="message__subject">The pills worked well! Thank you!</span>
            <span class="message__date">Feb 13, 2022, 07:47 PM</span>
          </a>
        </li>
      </ul>
    </div>
  </main>
</body>

</html>

doctors/templates/doctors/otp_page.html
{% load static %}
<html lang="en">

    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      
        <!-- Favicon -->
        <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
        <!-- Icon - IconMonster -->
        <link rel="stylesheet" href="https://cdn.iconmonstr.com/1.3.0/css/iconmonstr-iconic-font.min.css" />
        <!-- Mumble UI -->
        <link rel="stylesheet" href="{% static 'uikit/styles/uikit.css' %}" />
        <!-- Dev Search UI -->
        <link rel="stylesheet" href="{% static "styles/app.css" %}" />
      
        <title>Find Patient!</title>
      </head>

<body>
    <!-- Header Section -->
    <header class="header">
        <div class="container container--narrow">
          <a href="{% url 'self_doc' %}" class="header__logo">
            <img src="{% static 'images/logo.png' %}" alt="DevSearch Logo" />
          </a>
          <nav class="header__nav">
            <input type="checkbox" id="responsive-menu" />
            <label for="responsive-menu" class="toggle-menu">
              <span>Menu</span>
              <div class="toggle-menu__lines"></div>
            </label>
            <ul class="header__menu">
              <li class="header__menuItem"><a href="{% url 'find_patient' %}">Find Patients</a></li>
              <li class="header__menuItem"><a href="{% url 'inbox' %}">Inbox</a></li>
              <li class="header__menuItem"><a href="{% url 'landing' %}" class="btn btn--sub">Logout</a></li>
            </ul>
          </nav>
        </div>
      </header>

    <!-- Main Section -->
    <main class="formPage my-xl">
        <div class="content-box">


                <form class="form" method="POST">
                    <!-- Input:Text -->
                    <div class="form__field">
                        <label for="formInput#text">Enter OTP on the Patient's Email: </label>
                        <input class="input input--text" id="formInput#text" name="otp" type="password" name="text"
                            placeholder="Enter OTP on the Patient's Email" />
                    </div>

                    <a href="{% url 'otp_result' %}"><input class="btn btn--sub btn--lg  my-md" type="button" value="Next" /></a>
                </form>
            </div>
        </div>
    </main>
</body>

</html>

doctors/templates/doctors/otp_result.html
{% load static %}
<html lang="en">

    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      
        <!-- Favicon -->
        <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
        <!-- Icon - IconMonster -->
        <link rel="stylesheet" href="https://cdn.iconmonstr.com/1.3.0/css/iconmonstr-iconic-font.min.css" />
        <!-- Mumble UI -->
        <link rel="stylesheet" href="{% static 'uikit/styles/uikit.css' %}" />
        <!-- Dev Search UI -->
        <link rel="stylesheet" href="{% static "styles/app.css" %}" />
        <link rel="stylesheet" href='{% static "styles/kanwar.css" %}' />
      
        <title>Patient Profile!</title>
      </head>

<body>
    <!-- Header Section -->
    <header class="header">
        <div class="container container--narrow">
          <a href="{% url 'self_doc' %}" class="header__logo">
            <img src="{% static 'images/logo.png' %}" alt="DevSearch Logo" />
          </a>
          <nav class="header__nav">
            <input type="checkbox" id="responsive-menu" />
            <label for="responsive-menu" class="toggle-menu">
              <span>Menu</span>
              <div class="toggle-menu__lines"></div>
            </label>
            <ul class="header__menu">
              <li class="header__menuItem"><a href="{% url 'find_patient' %}">Find Patients</a></li>
              <li class="header__menuItem"><a href="{% url 'inbox' %}">Inbox</a></li>
              <li class="header__menuItem"><a href="{% url 'landing' %}" class="btn btn--sub">Logout</a></li>
            </ul>
          </nav>
        </div>
      </header>

    <!-- Main Section -->
    <main class="settingsPage profile my-md">
        <div class="container">
          <div class="layout">
            <div class="column column--1of3">
              <div class="card text-center">
                <div class="card__body dev">
                  <img class="avatar avatar--xl dev__avatar" src="{{patient.profile_image.url}}" />
                  <h2 class="dev__name">{{patient.name}}</h2>
                  <br>
                  <p class="dev__title">Age: {{patient.age}}</p>
                  <p class="dev__title">DOB: {{patient.dob}}</p>
                  <p class="dev__title">Height: {{patient.height}} cms</p>
                  <p class="dev__title">Weight: {{patient.weight}} Kgs</p>
                  <p class="dev__title">Blood group: A+</p>
      
                  <br>
                  <p class="dev__title">{{patient.email}}</p>
                  <p class="dev__title">Phone Number: {{patient.phone_number}}</p>
                  <br>
                  <p class="dev__location">Based in {{patient.address}}</p>
                  
                </div>
              </div>
            </div>
            <div class="column column--2of3">
              <div class="devInfo">
                <h5 class="devInfo__title">{{patient.name}}'s Medical History</h5>
                <p class="devInfo__about"></p>
              </div>
              <div class="settings">
                <h3 class="settings__title">Doctors Consulted Previously</h3>
              </div>
      
              <table class="settings__table">
                <tr>
                  <td class="settings__tableInfo" >
                    <img class="card cardDocDet" src="{{doctor.profile_image.url}}" href="{% url 'doc_profile' doctor.id %}">
                    <div>
                      <h4>DR. {{doctor.name}}</h4>
                    <p>
                      {% for spec in doctor.special_set.all %}
                      {{spec}}
                      {% endfor %}
                    </p>
                    </div>
                    
                  </td>
                  <td class="settings__tableActions">
                  </td>
                </tr>
       
              </table>
      
              <div class="settings">
                <h3 class="settings__title">Reports</h3>
              </div>
      
              <table class="settings__table">
                {% for report in reports %}
                <tr>
                  <td class="settings__thumbnail">
                    <a href="http://127.0.0.1:8000/images/{{report.report}}" ><img src="{% static 'images/folder.png' %}" alt="Report Default" /></a>
                  </td>
                  <td class="settings__tableInfo">
                    <a href="http://127.0.0.1:8000/images/{{report.report}}">{{report.title}}</a>
                  </td>
                  <td>
                    Date: {{report.created_at}}
                  </td>
                  <td class="settings__tableActions">
                  </td>
                </tr>
                {% endfor %}
              </table>
            </div>
          </div>
        </div>
      </main>
</body>

</html>

doctors/templates/doctors/self_doc.html
{% load static %}
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <!-- Favicon -->
  <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
  <!-- Icon - IconMonster -->
  <link rel="stylesheet" href="https://cdn.iconmonstr.com/1.3.0/css/iconmonstr-iconic-font.min.css" />
  <!-- Mumble UI -->
  <link rel="stylesheet" href="{% static 'uikit/styles/uikit.css' %}" />
  <!-- Dev Search UI -->
  <link rel="stylesheet" href="{% static "styles/app.css" %}" />

  <title>{{profile.name}}</title>
</head>

<body>
  <!-- Header Section -->
  <header class="header">
    <div class="container container--narrow">
      <a href="{% url 'self_doc' %}" class="header__logo">
        <img src="{% static 'images/logo.png' %}" alt="DevSearch Logo" />
      </a>
      <nav class="header__nav">
        <input type="checkbox" id="responsive-menu" />
        <label for="responsive-menu" class="toggle-menu">
          <span>Menu</span>
          <div class="toggle-menu__lines"></div>
        </label>
        <ul class="header__menu">
          <li class="header__menuItem"><a href="{% url 'find_patient' %}">Find Patients</a></li>
          <li class="header__menuItem"><a href="{% url 'inbox' %}">Inbox</a></li>
          <li class="header__menuItem"><a href="{% url 'landing' %}" class="btn btn--sub">Logout</a></li>
        </ul>
      </nav>
    </div>
  </header>

<main class="settingsPage profile my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <div class="card text-center">
            <div class="card__body dev">
              <a class="tag tag--pill tag--main settings__btn" href="#"><i class="im im-edit"></i> Edit</a>
              <img class="avatar avatar--xl dev__avatar" src="{{profile.profile_image.url}}" />
              <h2 class="dev__name">{{profile.name}}</h2>
              <p class="dev__title">{{profile.qualification}}</p>
              <p class="dev__location">Works at {{profile.current_hospital}}</p>
              <p class="dev__location">Studied at {{profile.college}}</p>
            </div>
          </div>
        </div>
        <div class="column column--2of3">
          <div class="devInfo">
            <p class="devInfo__about">
                Member since  {{profile.created}}
             </p>
             <br>
            <h3 class="devInfo__title">About Me</h3>
            <p class="devInfo__about">
               {{profile.short_intro}}
               <br>
               <br>
              {{profile.bio}}
            </p>
          </div>
          <div class="settings">
            <h3 class="settings__title">Specializations</h3>
            <a class="tag tag--pill tag--sub settings__btn tag--lg" href="#"><i class="im im-plus"></i> Add Skill</a>
          </div>

          <table class="settings__table">
            {% for spec in profile.special_set.all %}
            <tr>
              <td class="settings__tableInfo">
                <h4>{{spec.name}}</h4>
                <p>
                  {{spec.description}}
                </p>
              </td>
              <td class="settings__tableActions">
                <a class="tag tag--pill tag--main settings__btn" href="#"><i class="im im-edit"></i> Edit</a>
                <a class="tag tag--pill tag--main settings__btn" href="#"><i class="im im-x-mark-circle-o"></i>
                  Delete</a>
              </td>
            </tr>
            {% endfor %}
          </table>

         
        </div>
      </div>
    </div>
  </main>
</body>

</html>